version: 2

sources:
  - name: landing
    database: dbtcloud 
    schema: landing  
    tables:
      - name: customers
      - name: order_items
      - name: orders
      - name: products